apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-web-v2
  labels:
    app: events-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-web
      ver: v2.0
  template:
    metadata:
      labels:
        app: events-web
        ver: v2.0
    spec:
      containers:
        - name: events-web
          image: ladeavinash/events-website:v2.0
          ports:
            - containerPort: 8080
          env:
          - name: SERVER
            value: "http://events-api-svc:8082"